/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminBannersRouteImport } from './routes/_admin/banners'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminInquiriesRouteImport } from './routes/_admin/inquiries'
import { Route as AdminMembersRouteImport } from './routes/_admin/members'
import { Route as AdminPackagesRouteImport } from './routes/_admin/packages'
import { Route as AdminServicesRouteImport } from './routes/_admin/services'
import { Route as AdminSocietiesRouteImport } from './routes/_admin/societies'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSocietiesRoute = AdminSocietiesRouteImport.update({
  id: '/societies',
  path: '/societies',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/banners': typeof AdminBannersRoute
  '/dashboard': typeof AdminDashboardRoute
  '/inquiries': typeof AdminInquiriesRoute
  '/members': typeof AdminMembersRoute
  '/packages': typeof AdminPackagesRoute
  '/services': typeof AdminServicesRoute
  '/societies': typeof AdminSocietiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/banners': typeof AdminBannersRoute
  '/dashboard': typeof AdminDashboardRoute
  '/inquiries': typeof AdminInquiriesRoute
  '/members': typeof AdminMembersRoute
  '/packages': typeof AdminPackagesRoute
  '/services': typeof AdminServicesRoute
  '/societies': typeof AdminSocietiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/banners': typeof AdminBannersRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/inquiries': typeof AdminInquiriesRoute
  '/_admin/members': typeof AdminMembersRoute
  '/_admin/packages': typeof AdminPackagesRoute
  '/_admin/services': typeof AdminServicesRoute
  '/_admin/societies': typeof AdminSocietiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/banners'
    | '/dashboard'
    | '/inquiries'
    | '/members'
    | '/packages'
    | '/services'
    | '/societies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/banners'
    | '/dashboard'
    | '/inquiries'
    | '/members'
    | '/packages'
    | '/services'
    | '/societies'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/banners'
    | '/_admin/dashboard'
    | '/_admin/inquiries'
    | '/_admin/members'
    | '/_admin/packages'
    | '/_admin/services'
    | '/_admin/societies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/banners': {
      id: '/_admin/banners'
      path: '/banners'
      fullPath: '/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/inquiries': {
      id: '/_admin/inquiries'
      path: '/inquiries'
      fullPath: '/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/members': {
      id: '/_admin/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/packages': {
      id: '/_admin/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/services': {
      id: '/_admin/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/societies': {
      id: '/_admin/societies'
      path: '/societies'
      fullPath: '/societies'
      preLoaderRoute: typeof AdminSocietiesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSocietiesRoute: typeof AdminSocietiesRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSocietiesRoute: AdminSocietiesRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
