// ignore_for_file: type=lint
// PLACEHOLDER FILE — DO NOT SHIP THIS TO PRODUCTION.
//
// This file is normally auto-generated by running:
//   flutterfire configure
// after creating a Firebase project (see README.md, "Firebase setup").
// That command overwrites this file with real project credentials for
// Android, iOS, and Web. The values below are dummy placeholders that
// let the project structure compile before Firebase is connected.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'Run `flutterfire configure` to generate real options.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'maha-maintain-pro',
    authDomain: 'maha-maintain-pro.firebaseapp.com',
    storageBucket: 'maha-maintain-pro.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'maha-maintain-pro',
    storageBucket: 'maha-maintain-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'maha-maintain-pro',
    storageBucket: 'maha-maintain-pro.appspot.com',
    iosBundleId: 'com.mahamaintainpro.app',
  );
}
